"""HW1 class tweaks: ``tweak/<class>.xml`` (and ``shared.xml``).

``params`` replaces the class's starting stats and ``upgrades`` replaces the
shop's upgrade list. A mission ships full copies of the stock files, so a value
equal to the stock one was usually left alone, not chosen."""

from __future__ import annotations

import json
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path

CLASSES = ("knight", "priest", "ranger", "sorcerer", "thief", "warlock", "wizard")
FILES = CLASSES + ("shared",)

Value = int | float | bool | str


@dataclass
class Upgrade:
    id: str
    cost: int
    cat: str
    req: str
    values: dict[str, Value] = field(default_factory=dict)
    extra: dict[str, str] = field(default_factory=dict)  # other attributes, e.g. life-cost-scale


@dataclass
class Tweak:
    params: dict[str, Value] = field(default_factory=dict)
    upgrades: list[Upgrade] = field(default_factory=list)

    def upgrade(self, uid: str) -> Upgrade | None:
        for u in self.upgrades:
            if u.id == uid:
                return u
        return None


def _value(el: ET.Element) -> Value:
    s = (el.text or "").strip()
    if el.tag == "int":
        return int(float(s or 0))
    if el.tag == "float":
        return float(s or 0)
    if el.tag == "bool":
        return s.lower() in ("true", "1", "t")
    return s


def _values(el: ET.Element) -> dict[str, Value]:
    return {c.get("name"): _value(c) for c in el if c.get("name") and c.get("name") != "lvl"}


def parse(text: str) -> Tweak:
    root = ET.fromstring(text)
    t = Tweak()
    p = root.find("params/dictionary")
    if p is not None:
        t.params = _values(p)
    ups = root.find("upgrades")
    for d in (ups if ups is not None else []):
        if d.get("id") is None:
            continue
        cost = d.get("cost", "0")
        extra = {k: v for k, v in d.attrib.items() if k not in ("id", "cost", "cat", "req", "name", "desc")}
        t.upgrades.append(Upgrade(d.get("id"), int(float(cost)) if cost else 0, d.get("cat", ""),
                                  d.get("req", ""), _values(d), extra))
    return t


def load_dir(tweak_dir: Path) -> dict[str, Tweak]:
    """The mission's tweak files by class name (``knight``, ..., ``shared``)."""
    out: dict[str, Tweak] = {}
    for name in FILES:
        f = tweak_dir / f"{name}.xml"
        if f.exists():
            out[name] = parse(f.read_text(encoding="utf-8-sig", errors="replace"))
    return out


# -- stock tables ----------------------------------------------------------
# The stock HW1 files define the upgrade tiers a mission's values are compared
# against. They are kept as JSON so converting doesn't need HW1's assets
# extracted; ``dump_stock`` rebuilds it from <HW1>/editor/assetsExtract/tweak.

STOCK_JSON = Path(__file__).parent.parent / "mapping" / "data" / "hw1_tweak_stock.json"


def to_json(t: Tweak) -> dict:
    return {"params": t.params,
            "upgrades": [{"id": u.id, "cost": u.cost, "cat": u.cat, "req": u.req, "values": u.values,
                          **({"extra": u.extra} if u.extra else {})} for u in t.upgrades]}


def from_json(d: dict) -> Tweak:
    return Tweak(dict(d["params"]), [Upgrade(u["id"], u["cost"], u["cat"], u["req"], dict(u["values"]),
                                             dict(u.get("extra", {}))) for u in d["upgrades"]])


def dump_stock(tweak_dir: Path, out: Path = STOCK_JSON) -> None:
    data = {"_doc": "HW1's stock tweak/*.xml (assets.bin), generated by hw1.tweak.dump_stock."}
    data.update({k: to_json(v) for k, v in load_dir(tweak_dir).items()})
    out.write_text(json.dumps(data, indent=1) + "\n", encoding="utf-8")


def load_stock(path: Path = STOCK_JSON) -> dict[str, Tweak]:
    data = json.loads(path.read_text(encoding="utf-8"))
    return {k: from_json(v) for k, v in data.items() if not k.startswith("_")}
